name: hkview
description: hkview a mobile project

publish_to: 'none' 

version: 0.0.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"
# DEPENDECNCIES 
dependencies:
  flutter:
    sdk: flutter
  # Bağımlı  
  webview_flutter: ^1.0.7
  # Bağımlı Icon
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  # Resimlerin b
  assets:
    - assets/
  uses-material-design: true